### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by sean-m** [adamhathcock/Nancy.OData#2]
I can't find any documentation on how I might go about using this. I'm a little new to Nancy and I'm not entirely sure where this fits in but this looks better than trying to do query string parsing by myself. A usage example would be helpful and I'm willing to document it further once I understand how it works.

**Comment by adamhathcock** [comment]
The only example is this: https://github.com/adamhathcock/Nancy.OData/blob/master/Nancy.OData.Test/TestModule.cs

I did this a long time ago so I'm not sure how useful it is now.  The intent is to some of expose the OData query syntax to anything, like a collection, instead of just direct to a SQL database.

**Comment by adamdriscoll** [comment]
I have it working with a EF6 data context. 

Just use the Response.AsOData as @adamhathcock mentioned. 
```C#
Get["/", true] = async (x, ct) => await Task.Run(() => Response.AsOData(dc.Users));
```

Then just invoke your endpoint and specify 'application/json' in the accept header. 

```powershell
Invoke-RestMethod "http://localhost:1234/user?`$filter=Name%20eq%20%27MADVDI\adriscoll%27&`$skip=1&`$top=1&`$Orderby=Name" -Headers @{'accept'='application/json'}
```

Based on the SQL generated by the EF LINQ provider, I'd say this is working great!

```sql
SELECT 
[Extent1].[Id] AS [Id],
[Extent1].[Name] AS [Name]
FROM [dbo].[Users] AS [Extent1]
WHERE 'MADVDI\adriscoll' = [Extent1].[Name]
ORDER BY [Extent1].[Name] ASC
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY
```

**Comment by sean-m** [comment]
Great. That points me in the right direction.
